/*
 * thermo3.h
 *
 * Driver for the Thermo 3 Click (MIKROE-1885) with the TMP102 sensor.
 * MCSD project - input module.
 *
 * Idea of this module: everything that knows something about the TMP102
 * (I2C address, register numbers, how the 12 bits are packed) lives here.
 * main.c only asks for a temperature and does not care how it is read.
 * That is also the reason why there is no printf and no display stuff in
 * this file - otherwise the module could not be tested on its own.
 */

#ifndef THERMO3_H
#define THERMO3_H

/* main.h is generated by CubeMX and pulls in the right HAL header for our
 * board, so I do not have to hardcode stm32f4xx_hal.h here. */
#include "main.h"
#include <stdint.h>

/* Return values. I use plain numbers instead of an enum, it is enough here. */
#define THERMO3_OK    0u
#define THERMO3_ERROR 1u

/* Starts the driver. hi2c is the handle CubeMX generated (normally &hi2c1).
 * Writes the configuration register and reads it back to check that the
 * sensor really answers on the bus. */
uint8_t thermo3_init(I2C_HandleTypeDef *hi2c);

/* Reads the temperature register and gives back the raw 12 bit value,
 * already right justified and sign extended (so it can be negative). */
uint8_t thermo3_read_raw(int16_t *raw);

/* Converts the raw value into hundredths of a degree Celsius.
 * Example: 2344 means 23.44 degC.
 * I work with integers on purpose - float printing over UART needs an extra
 * linker flag on the STM32 and I do not want that complication. */
int32_t thermo3_raw_to_centi_c(int16_t raw);

/* Celsius -> Fahrenheit, both in hundredths of a degree. */
int32_t thermo3_centi_c_to_centi_f(int32_t centi_c);

/* Convenience version if we ever want a float after all. */
uint8_t thermo3_read_celsius(float *celsius);

/* Sets the two limits for the ALERT output, in hundredths of a degree.
 * The sensor is in comparator mode, that means: ALERT becomes active when
 * the temperature goes above high_centi_c and only goes away again when it
 * falls below low_centi_c. So the two values are our hysteresis. */
uint8_t thermo3_set_limits(int32_t low_centi_c, int32_t high_centi_c);

/* Tells the driver where the ALERT line of the sensor is connected.
 * Optional - if I never call this, the driver falls back to reading the
 * alert flag over I2C. On our shield the INT pin of click port 2 is PA4,
 * so the call looks like: thermo3_set_alert_pin(GPIOA, GPIO_PIN_4); */
void thermo3_set_alert_pin(GPIO_TypeDef *port, uint16_t pin);

/* Returns 1 = alert active, 0 = not active (or read failed).
 * If the pin was registered with thermo3_set_alert_pin() the pin is read,
 * otherwise the AL flag is read out of the configuration register. */
uint8_t thermo3_alert_active(void);

#endif /* THERMO3_H */
